services:
  app:
    image: "${IMAGE_URL}:latest"
    container_name: ${REPO_NAME}
    # access at :8755
    network_mode: host
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      SENTRY_DSN: ${SENTRY_DSN}
    restart: on-failure:5
